### ISSUE TITLE
breadcrumb.html

### ISSUE THREAD

**Issue by Galixte** [david63/david63-userranks#3]
Hi @david63,

what is this file, please ? https://github.com/david63/david63-userranks/blob/master/david63/userranks/breadcrumb.html

**Comment by Galixte** [comment]
Ok it’s an addon for this extension https://github.com/PayBas/BreadcrumbMenu thanks !-)

**Comment by Galixte** [comment]
Hi @david63,

it seem the backround for Ranks list link in the breadcrumb menu is not the same than others link.

Could you take a look, please ?

**Comment by david63** [comment]
I have little time at the moment for extensions as there some other things going on in my life that take precedence - but when time permits I will take a look.

Incidentally this is unofficial and was something that I did for my own site

**Comment by Galixte** [comment]
Thanks ;)

**Comment by Galixte** [comment]
Hi @david63,

could you take a look, please ?

**Comment by Galixte** [comment]
Hi @david63,

could you take a look, please ?

**Comment by Galixte** [comment]
Hi @david63,

ok you have deleted this file, but is it possible to have an answer for my request, please ?

**Comment by david63** [comment]
It all looks OK to me - perhaps it is style related

**Comment by Galixte** [comment]
Ok, i will take a look for other styles than prosilver, thanks.
