### ISSUE TITLE
viewprofile links don’t work

### ISSUE THREAD

**Issue by Galixte** [david63/david63-userranks#6]
Hi,

on Ranks list page: http://www.domain.tld/userranks/ranks.

If i click on Member name the link to his profil (viewprofile) doesn’t works: instead of this http://www.domain.tld/memberlist.php?mode=viewprofile&u=2 i have this http://www.domain.tld/userranks/memberlist.php?mode=viewprofile&u=2.

NOTE: my PR fixes this problem, but after all other pages redirect to the Ranks list page.

**Comment by Galixte** [comment]
Salut @Zoddo,

tu as une idée pour corriger le soucis ? 

L’extension ne prend pas en compte le fait que nous sommes à la page : http://www.domain.tld/userranks/ranks si l’on clique sur un nom d’utilisateur l’adresse se trouve être : http://www.domain.tld/userranks/memberlist.php?mode=viewprofile&u=2 au lieu de http://www.domain.tld/memberlist.php?mode=viewprofile&u=2.

%on PR ci-dessus corrige le problème mais toutes autres pages créées sur le forum renvoie vers la page des Rangs. Mon PR modifie ctte ligne : http://www.domain.tld/userranks/memberlist.php?mode=viewprofile&u=2.

Mais je pense qu’il y a un oubli dans le code pour prendre en compte le fait que nous sommes dans /userranks/ à partir de cette ligne-ci : https://github.com/david63/david63-userranks/blob/master/david63/userranks/controller/main_controller.php#L95.

L’auteur étant peut disponible, voilà pourquoi je m’adresse à toi. ;)

**Comment by Zoddo** [comment]
@Galixte Normalement, c'est gérer automatiquement par phpBB ... Je ne vois pas de code spécial pour gérer ça dans l'extension [phpbb-extensions/pages](https://github.com/phpbb-extensions/pages).

**Comment by Zoddo** [comment]
Check this ticket: https://tracker.phpbb.com/browse/PHPBB3-13683

**Comment by Galixte** [comment]
Ok, étrange pas de retour des développeurs de phpBB. J'ai posté un commentaire vers cette issue. Merci.

**Comment by Galixte** [comment]
Ok, j’ai toruvé la source du problème: https://github.com/tas2580/userinfo/issues/2.
